# Generated by Django 5.1.4 on 2025-12-25 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentimentmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='sentimentmodel',
            old_name='trained_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='C_parameter',
        ),
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='classification_report',
        ),
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='confusion_matrix',
        ),
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='contribution_rate',
        ),
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='gamma',
        ),
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='kernel',
        ),
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='original_dimensions',
        ),
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='reduced_dimensions',
        ),
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='test_samples',
        ),
        migrations.RemoveField(
            model_name='sentimentmodel',
            name='training_samples',
        ),
        migrations.AddField(
            model_name='sentimentmodel',
            name='algorithm',
            field=models.CharField(default='svm', max_length=50),
        ),
        migrations.AddField(
            model_name='sentimentmodel',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sentimentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sentimentmodel',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sentimentmodel',
            name='f1_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sentimentmodel',
            name='model_file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sentimentmodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sentimentmodel',
            name='precision',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sentimentmodel',
            name='recall',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sentimentmodel',
            name='trained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
