# Generated by Django 5.1.4 on 2025-12-26 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sentimentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='predicted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='predicted_by_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_predictions', to='core.sentimentmodel'),
        ),
        migrations.AddField(
            model_name='review',
            name='predicted_label',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='prediction_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
