# Generated by Django 5.1.4 on 2025-12-26 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review_predicted_at_review_predicted_by_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True)),
                ('predicted_sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('source', models.CharField(default='web', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_feedback', models.CharField(blank=True, choices=[('correct', 'Correct'), ('incorrect', 'Incorrect')], max_length=20, null=True)),
                ('corrected_sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.sentimentmodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_predic_created_2fa12a_idx'), models.Index(fields=['model', 'predicted_sentiment'], name='core_predic_model_i_49e482_idx')],
            },
        ),
    ]
